### ISSUE TITLE
Maybe certain bugs exists in the RoIPool cuda source file "roi_pool_kernel.cu"

### ISSUE THREAD

**Issue by mangwang** [open-mmlab/mmdetection#1007]
When I change the `roi_layer` from `dict(type='RoIAlign', out_size=14, sample_num=2)` to `dict(type='RoIPool', out_size=14)` in the config file "faster_rcnn_r50_caffe_c4_1x.py" and remain other settings unchanged, there will be a cuda memory error occurs, which shows:

> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=265 error=77 : an illegal memory access was encountered

While if I switch to the Torchvision RoIPool by setting `roi_layer=dict(type='RoIPool', out_size=14, use_torchvision=True)`, there would be no errors.

Thus I guess there maybe certain bugs exists in the RoIPool cuda source file, could you please double check it? Thanks.

**Comment by hellock** [comment]
Thanks for the reporting, we will have a check.

**Comment by xvjiarui** [comment]
This issue is fixed in the latest version. You may have a try.
