### ISSUE TITLE
Distributed training hangs with `NCCL WARN Could not find a path for pattern 4, falling back to simple order`

### ISSUE THREAD

**Issue by matthost** [open-mmlab/mmdetection#11461]
In SageMaker using Training API with 4 machines, 8 gpus each. Will update deps, but posting in case others have the same issue. MMDet 2.x

```

  | 2024-02-03T00:28:50.822Z | sys.platform: linux
-- | -- | --
  | 2024-02-03T00:28:50.822Z | Python: 3.8.10 (default, Jun 4 2021, 15:09:15) [GCC 7.5.0]
  | 2024-02-03T00:28:50.822Z | CUDA available: True
  | 2024-02-03T00:28:50.822Z | GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-40GB
  | 2024-02-03T00:28:50.822Z | CUDA_HOME: /usr/local/cuda
  | 2024-02-03T00:28:50.822Z | NVCC: Build cuda_11.1.TC455_06.29190527_0
  | 2024-02-03T00:28:50.822Z | GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  | 2024-02-03T00:28:50.822Z | PyTorch: 1.9.1
  | 2024-02-03T00:28:50.822Z | PyTorch compiling details: PyTorch built with:
  | 2024-02-03T00:28:50.822Z | - GCC 9.3
  | 2024-02-03T00:28:50.822Z | - C++ Version: 201402
  | 2024-02-03T00:28:50.822Z | - Intel(R) oneAPI Math Kernel Library Version 2022.0-Product Build 20211112 for Intel(R) 64 architecture applications
  | 2024-02-03T00:28:50.822Z | - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  | 2024-02-03T00:28:50.822Z | - OpenMP 201511 (a.k.a. OpenMP 4.5)
  | 2024-02-03T00:28:50.822Z | - NNPACK is enabled
  | 2024-02-03T00:28:50.822Z | - CPU capability usage: AVX2
  | 2024-02-03T00:28:50.822Z | - CUDA Runtime 11.1
  | 2024-02-03T00:28:50.822Z | - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_70,code=compute_70
  | 2024-02-03T00:28:50.822Z | - CuDNN 8.0.5
  | 2024-02-03T00:28:50.822Z | - Magma 2.5.2
  | 2024-02-03T00:28:50.822Z | - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, FORCE_FALLBACK_CUDA_MPI=1, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=1, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=ON, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
  | 2024-02-03T00:28:50.822Z | TorchVision: 0.10.1+cu111
  | 2024-02-03T00:28:50.822Z | OpenCV: 4.5.5
  | 2024-02-03T00:28:50.822Z | MMCV: 1.4.5
  | 2024-02-03T00:28:50.822Z | MMCV Compiler: GCC 9.4
  | 2024-02-03T00:28:50.822Z | MMCV CUDA Compiler: 11.1
  | 2024-02-03T00:28:50.822Z | MMDetection: 2.25.0+


```

After these logs training hangs forever:

```
2024-02-03T00:28:59.831Z | NCCL version 2.7.8+cuda11.1
-- | --
  | 2024-02-03T00:29:01.832Z | algo-1:139:339 [7] graph/search.cc:765 NCCL WARN Could not find a path for pattern 4, falling back to simple order
  | 2024-02-03T00:29:01.832Z | algo-1:133:343 [1] graph/search.cc:765 NCCL WARN Could not find a path for pattern 4, falling back to simple order
  | 2024-02-03T00:29:01.832Z | algo-1:135:340 [3] graph/search.cc:765 NCCL WARN Could not find a path for pattern 4, falling back to simple order
  | 2024-02-03T00:29:01.832Z | algo-1:137:338 [5] graph/search.cc:765 NCCL WARN Could not find a path for pattern 4, falling back to simple order
  | 2024-02-03T00:29:01.832Z | algo-1:138:337 [6] graph/search.cc:765 NCCL WARN Could not find a path for pattern 4, falling back to simple order
  | 2024-02-03T00:29:01.832Z | algo-1:134:341 [2] graph/search.cc:765 NCCL WARN Could not find a path for pattern 4, falling back to simple order
  | 2024-02-03T00:29:01.832Z | algo-1:132:336 [0] graph/search.cc:765 NCCL WARN Could not find a path for pattern 4, falling back to simple order
  | 2024-02-03T00:29:01.832Z | algo-1:136:342 [4] graph/search.cc:765 NCCL WARN Could not find a path for pattern 4, falling back to simple order
```

**Comment by matthost** [comment]
This turned out to be an issue with the AWS Security Group setup. `p4d` instances use something called EFA for networking, and security group requires "All Traffic" rules for ingress and egress within the security group. The default CDK all traffic does not work, as it's an ipv4 out on 0.0.0.0/0, not to the security group itself. After upgrading to latest torch and mmdet I got a better warning that led to this fix.
