### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by julien-couillaud-2e** [open-mmlab/mmdetection#11573]
**Describe the bug**
While running the demo to check if mmdet was correctly installed, I am getting the following error from CUDA:
RuntimeError: CUDA error: an illegal memory access was encountered

**Reproduction**

1. What command or script did you run?

```
CUDA_LAUNCH_BLOCKING=1 python demo/image_demo.py demo/demo.jpg rtmdet_tiny_8xb32-300e_coco.py --weights rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth --device cuda:0
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No modifications done to the code or the config.

3. What dataset did you use?
I used the pretrained models

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1: Tesla K80
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 1.12.1+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu113
OpenCV: 4.9.0
MMEngine: 0.10.3
MMDetection: 3.3.0+cfd5d3a

2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   Pytorch was installed via pip with the following:
   pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113

**Error traceback**

```
Traceback (most recent call last):
  File "/home/julien_couillaud/mmdetection/demo/image_demo.py", line 192, in <module>
    main()
  File "/home/julien_couillaud/mmdetection/demo/image_demo.py", line 184, in main
    inferencer(**call_args)
  File "/home/julien_couillaud/mmdetection/mmdet/apis/det_inferencer.py", line 403, in __call__
    preds = self.forward(data, **forward_kwargs)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/mmengine/infer/infer.py", line 296, in forward
    return self.model.test_step(inputs)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/mmengine/model/base_model/base_model.py", line 361, in _run_forward
    results = self(**data, mode=mode)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/julien_couillaud/mmdetection/mmdet/models/detectors/base.py", line 94, in forward
    return self.predict(inputs, data_samples)
  File "/home/julien_couillaud/mmdetection/mmdet/models/detectors/single_stage.py", line 109, in predict
    x = self.extract_feat(batch_inputs)
  File "/home/julien_couillaud/mmdetection/mmdet/models/detectors/single_stage.py", line 146, in extract_feat
    x = self.backbone(batch_inputs)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/julien_couillaud/mmdetection/mmdet/models/backbones/cspnext.py", line 192, in forward
    x = layer(x)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/julien_couillaud/mmcv/mmcv/cnn/bricks/conv_module.py", line 281, in forward
    x = self.conv(x)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/julien_couillaud/anaconda3/envs/Impact_AI/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: an illegal memory access was encountered
```

**Additional details**
We have yet to learn how this error could be produced. We tried a few basic codes in PyTorch like the following:
```
  import torch.nn as nn
  import torch.nn.functional as F
  from torch.autograd import Variable
  import torch
  import pdb
  pst=pdb.set_trace
  import os
  torch.cuda.empty_cache()
  os.environ['CUDA_LAUNCH_BLOCKING']='1'
  device = 'cuda:0'
  convx = nn.Conv2d(1, 100, (5,128)).to(device)
  torch.cuda.empty_cache()
  y = convx(torch.randn(64, 1, 128, 128).to(device))
```
With the above code, we can see that memory is allocated to the GPU. Do you have any idea what could be the issue?

**Comment by julien-couillaud-2e** [comment]
Anybody ??

**Comment by XLBL2333** [comment]
Did you solve this problem,bro?
I'm getting the same error "File "C:\Users\MyPC\miniconda3\envs\yolov5new\lib\site-packages\torch\nn\modules\conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: an illegal memory access was encountered"

**Comment by julien-couillaud-2e** [comment]
Hi,

I fixed the issue by changing the version of python and pytorch.
I am using python3 10.13 and pytorch 1.13 compatible.
Try to play with pytorch version until you find a version which works with your CUDA setup.

Best regards,
Julien
