### ISSUE TITLE
Train a model to detect person(only one class) using COCO dataset

### ISSUE THREAD

**Issue by LifeIsSoSolong** [open-mmlab/mmdetection#1281]
Thanks for your contributions~
I want to train a faster_rcnn detector to detect "person"(only one class) using original coco datasets, and I counter some problems.
My train process are:
0.I can train and test original base model normally.

1. create mmdet/datasets/my_dataset.py and write:

```
from .coco import CocoDataset
from .registry import DATASETS

@DATASETS.register_module
class MyDataset(CocoDataset):
    CLASSES = ('person')
```
2.In mmdet/datasets/__init__.py"
add:
`from .my_dataset import MyDataset`

3.copy faster_rnn cfg (checkpoints/faster_rcnn_r50_fpn_1x.py) to a new dir, rename(faster_rcnn_r50_fpn_1x_person.py) and only change two places:
1)in model->bbox_head->numclasses 
`num_classes=81 => num_classes = 2`
2)in dataset setting 
`dataset_type = 'CocoDataset' => dataset_type = 'MyDataset'`

4. train
python tools/train.py configs/faster_rcnn_r50_fpn_1x_person.py --work_dir zkk_workdir/

then, I counter error:

```
2019-08-27 18:17:28,585 - INFO - Distributed training: False
2019-08-27 18:17:28,832 - INFO - load model from: torchvision://resnet50
2019-08-27 18:17:29,095 - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

FasterRCNN(....)
loading annotations into memory...
Done (t=9.56s)
creating index...
index created!
2019-08-27 18:17:41,537 - INFO - Start running, host: kaikai@kaikai, work_dir: /home/kaikai/anaconda3/envs/open-mmlab/mmdetection/zkk_workdir
2019-08-27 18:17:41,537 - INFO - workflow: [('train', 1)], max: 12 epochs
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCTensorMathCompare.cuh line=82 error=59 : device-side assert triggered
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [512,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [0,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [1,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [2,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [3,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [4,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [5,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [6,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/ClassNLLCriterion.cu:56: void ClassNLLCriterion_updateOutput_no_reduce_kernel(int, THCDeviceTensor<Dtype, 2, int, DefaultPtrTraits>, THCDeviceTensor<long, 1, int, DefaultPtrTraits>, THCDeviceTensor<Dtype, 1, int, DefaultPtrTraits>, Dtype *, int, int) [with Dtype = float]: block: [0,0,0], thread: [7,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main()
  File "tools/train.py", line 122, in main
    logger=logger)
  File "/home/kaikai/anaconda3/envs/open-mmlab/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/kaikai/anaconda3/envs/open-mmlab/mmdetection/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/kaikai/anaconda3/envs/open-mmlab/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kaikai/anaconda3/envs/open-mmlab/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/kaikai/anaconda3/envs/open-mmlab/mmdetection/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/kaikai/anaconda3/envs/open-mmlab/mmdetection/mmdet/models/detectors/two_stage.py", line 183, in forward_train
    *bbox_targets)
  File "/home/kaikai/anaconda3/envs/open-mmlab/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/kaikai/anaconda3/envs/open-mmlab/mmdetection/mmdet/models/bbox_heads/bbox_head.py", line 118, in loss
    pos_inds = labels > 0
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THC/THCTensorMathCompare.cuh:82
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /opt/conda/conda-bld/pytorch_1556653114079/work/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f908f03bdc5 in /home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x14792 (0x7f908bf19792 in /home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x50 (0x7f908f02b640 in /home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0x3067fb (0x7f908c6387fb in /home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x14019b (0x7f90be05819b in /home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x3bfc84 (0x7f90be2d7c84 in /home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x3bfcd1 (0x7f90be2d7cd1 in /home/kaikai/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #26: __libc_start_main + 0xf0 (0x7f90cd6be830 in /lib/x86_64-linux-gnu/libc.so.6)

已放弃 (核心已转储)
```
Maby I loss some steps when I training a new model for person using coco datasets, But I don't know how to figure it . 

Who can give me some advice.

Thanks for anyone who saw this issue.

**Comment by hellock** [comment]
You need to modify the coco annotation file and remove other gts except persons.

**Comment by LifeIsSoSolong** [comment]
> You need to modify the coco annotation file and remove other gts except persons.

Thanks , I have figure it out using your suggests. 

BTW, if I want to test voc using 'configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py', I don't find corresponding model in model zoo .  So I need to train model by myself，Is that right?
Thank you very much!

**Comment by LifeIsSoSolong** [comment]
> You need to modify the coco annotation file and remove other gts except persons.

Thanks , I have solved it using your suggests.

BTW, if I want to test voc using 'configs/pascal_voc/faster_rcnn_r50_fpn_1x_voc0712.py', I don't find corresponding model in model zoo . So I need to train model by myself，Is that right?
Thank you very much!

**Comment by hellock** [comment]
Yes, it would not take a long time to train on VOC.

**Comment by LifeIsSoSolong** [comment]
> Yes, it would not take a long time to train on VOC.

thank you very much~ best wishes

**Comment by deepakkupanda** [comment]
How to detect only the person class during inference? I am taking the already checkpoint and doing inference.
