### ISSUE TITLE
undefined symbol: _ZN3c1011CPUTensorIdEv 

### ISSUE THREAD

**Issue by TiG000** [open-mmlab/mmdetection#1577]
from . import deform_conv_cuda
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory
这个怎么解决呢

**Comment by TiG000** [comment]
ImportError: libcudart.so.10.0: cannot open shared object file: No such file or directory

**Comment by TiG000** [comment]
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
pytorch                   1.2.0           py3.7_cuda9.2.148_cudnn7.6.2_0    pytorch
![image](https://user-images.githubusercontent.com/43001385/67384119-26ce6880-f5c3-11e9-941b-8951e9e96acd.png)

**Comment by TiG000** [comment]
![image](https://user-images.githubusercontent.com/43001385/67384318-86c50f00-f5c3-11e9-9400-9f3cda0df564.png)

**Comment by TiG000** [comment]
该怎样解决呢

**Comment by ZwwWayne** [comment]
Hi @TiG000 ，
This might because the cuda version you are using is different during compilation and running time.
You can refer this issue https://github.com/open-mmlab/mmdetection/issues/592

Further, we would appreciate it if you could use the “Error report” issue template.

**Comment by TWDH** [comment]
@TiG000 
你好，我也遇到了相同的问题请问怎么解决呢？ 谢谢

**Comment by TiG000** [comment]
> @TiG000
> 你好，我也遇到了相同的问题请问怎么解决呢？ 谢谢
我已解决，应该是版本冲突吧~~我是卸载了cuda，重新安装了9.2版本，不用装cudnn，按照官方的格式选择了1.2版本的pytorch，自带cudnn。应该就可以了

**Comment by yustaub** [comment]
but my nvidia driver can install cuda 9.0.76 at most，can't insatll cuda 9.2,it must require cuda9.2?

**Comment by TiG000** [comment]
@yustaub 你可以试一下，应该保持一致就可以的

**Comment by yustaub** [comment]
@TiG000 请问您现在就是通过在caonda里重装了pytorch，安装cuda9.2的版本解决了吗

**Comment by TiG000** [comment]
@yustaub 是在自己新建的环境中按照官网格式指定安装了1.2版本的pytorch，只重新装了cuda9.2,发现应该是pytorch自带cudnn版本，应该不需要再重复装，更改对应cuda的path

**Comment by yustaub** [comment]
@TiG000 请问更改conda环境下的cuda的path是按照这个网址里这样子更改吗https://blog.csdn.net/u013832707/article/details/91445030

**Comment by TiG000** [comment]
@yustaub 
按这个装cuda：https://blog.csdn.net/wanzhen4330/article/details/81699769，不必要装cudnn。pytorch版本好像自带了~
按这个去验证是否都装成功了：https://blog.csdn.net/bat67/article/details/84065261

**Comment by yustaub** [comment]
@TiG000 按照第二个网址的验证都是正确的，可能是您说的那种情况吧，软链接的问题

**Comment by KKKiven** [comment]
> @TiG000 按照第二个网址的验证都是正确的，可能是您说的那种情况吧，软链接的问题

请问您现在解决了么？我遇到了同样的问题。

**Comment by TiG000** [comment]
@KKKiven 上面不是都写了问题可能原因及解决办法嘛

**Comment by KKKiven** [comment]
> @KKKiven 上面不是都写了问题可能原因及解决办法嘛

谢谢您的回复。我按照上面第二个网址验证都是正确的，但运行程序时还是报相同的错误。请问这个接下来应该如何解决呢？

**Comment by TiG000** [comment]
@KKKiven 验证成功只能说明成功安装了cuda和cudnn，运行环境需要版本匹配。我是单独只重装的cuda，pytorch最终选用的1.2版本，就应该能够解决了可能出现的两种报错情况，不清楚你的环境配置是什么情况，你多尝试下吧

**Comment by YilanWang** [comment]
and just remember, if you choose other versions cuda or cudnn, run 
> python setup.py develop
