### ISSUE TITLE
Keep getting error: segmentation fault

### ISSUE THREAD

**Issue by teddybear0212** [open-mmlab/mmdetection#1638]
I was trying to train an MaskRCNN model. However, I kept running into "Segmentation fault" and the whole process would just shut down spontaneously. I've tried compiling PyTorch from source and upgrade my gcc to 7.3.0, but neither of them seemed to help. The environment I'm currently working on is CentOS, gcc 7.3.0, PyTorch 1.3.0 and torchvision 0.4.1. The traceback is as following:

```
2019-11-07 21:54:34,120 - INFO - workflow: [('train', 1)], max: 12 epochs
loading annotations into memory...                                                                                                                              Done (t=0.00s)                                                                                                                                                  creating index...                                                                                                                                               index created!                                                                                                                                                  Traceback (most recent call last):
  File "./tools/train.py", line 108, in <module>
    main()
  File "./tools/train.py", line 104, in main
    logger=logger)                                                                                                                                                File "/home/teddybear12/mmdetection/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/teddybear12/mmdetection/mmdet/apis/train.py", line 227, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)                                                                                                      File "/home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.14-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv-0.2.14-py3.7-linux-x86_64.egg/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/teddybear12/mmdetection/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/teddybear12/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/teddybear12/mmdetection/mmdet/models/detectors/base.py", line 100, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/teddybear12/mmdetection/mmdet/models/detectors/two_stage.py", line 182, in forward_train
    proposal_list = self.rpn_head.get_bboxes(*proposal_inputs)
  File "/home/teddybear12/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/teddybear12/mmdetection/mmdet/models/anchor_heads/anchor_head.py", line 272, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/teddybear12/mmdetection/mmdet/models/anchor_heads/rpn_head.py", line 92, in get_bboxes_single
    proposals, _ = nms(proposals, cfg.nms_thr)
 File "/home/teddybear12/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 43, in nms
    inds = nms_cuda.nms(dets_th, iou_thr)
RuntimeError: CUDA error: invalid device function (launch_kernel at /pytorch/aten/src/ATen/native/cuda/Loops.cuh:102)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x2ac5f02de813 in /home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: void at::native::gpu_index_kernel<__nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> const&) + 0x7bb (0x2ac5aa7636bb in /home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x5481902 (0x2ac5aa75d902 in /home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x5481dc8 (0x2ac5aa75ddc8 in /home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x1aa972b (0x2ac5a6d8572b in /home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #5: at::native::index(at::Tensor const&, c10::ArrayRef<at::Tensor>) + 0x44e (0x2ac5a6d8055e in /home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x1fa087a (0x2ac5a727c87a in /home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x3a72fdd (0x2ac5a8d4efdd in /home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #8: at::Tensor::index(c10::ArrayRef<at::Tensor>) const + 0xbb (0x2ac5a8a15d6b in /home/teddybear12/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #9: nms_cuda(at::Tensor, float) + 0x730 (0x2ac60bd22a44 in /home/teddybear12/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #10: nms(at::Tensor const&, float) + 0xdf (0x2ac60bd11faf in /home/teddybear12/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x3bc9d (0x2ac60bd20c9d in /home/teddybear12/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0x393ba (0x2ac60bd1e3ba in /home/teddybear12/mmdetection/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux-gnu.so)
<omitting python frames>

/var/spool/slurm/d/job84751/slurm_script: line 12: 28620 Segmentation fault
```
What should I do? I can really use some help. This situation is very frustrating orz.

**Comment by teddybear0212** [comment]
@hellock

**Comment by ljc199504** [comment]
Modify the version of pytorch to 1.1,and compile the setup.py to generate build.py, you might solve this problem.

**Comment by arcsinx11** [comment]
> @hellock

Do you solve this problem?The environment I'm currently working on is ubuntu18.04, gcc 7.4.0, PyTorch 1.3.0 and torchvision 0.4.2.I have the same question.However ,When i try to modify the version of pytorch to 1.1, i got problem .The traceback is as following:

`(open-mmlab) liukaixuan@lkx:~/E/Deeplearn/Ceshi/mmdetection$ python tools/train.py configs/faster_rcnn_r50_fpn_1x.py
Traceback (most recent call last):
  File "tools/train.py", line 9, in <module>
    from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
  File "/home/liukaixuan/E/Deeplearn/Ceshi/mmdetection/mmdet/apis/__init__.py", line 2, in <module>
    from .inference import (inference_detector, init_detector, show_result,
  File "/home/liukaixuan/E/Deeplearn/Ceshi/mmdetection/mmdet/apis/inference.py", line 11, in <module>
    from mmdet.core import get_classes
  File "/home/liukaixuan/E/Deeplearn/Ceshi/mmdetection/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/liukaixuan/E/Deeplearn/Ceshi/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/liukaixuan/E/Deeplearn/Ceshi/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/liukaixuan/E/Deeplearn/Ceshi/mmdetection/mmdet/ops/__init__.py", line 2, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/liukaixuan/E/Deeplearn/Ceshi/mmdetection/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/liukaixuan/E/Deeplearn/Ceshi/mmdetection/mmdet/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
`

Anyone have some ideas?

**Comment by ljc199504** [comment]
你没有编译生成build里面的nms和deformableconv

**Comment by arcsinx11** [comment]
> 你没有编译生成build里面的nms和deformableconv

Thanks for your help.
I followed the steps of official Install mmdetection,and generated documents of "nms" and " dcn" in the "build".The procession of building had not errors.After that,i run test_nms.py and it produced the problem: nms_cuda is invalid device function(just like above).I installed CUDA10.0  in the PC from NVDIA and created a new conda virtual environment with CUDA 10.1.The version of python is 3.7. The traceback is as following:

`(open-mmlab) liukaixuan@lkx:~/E/Deeplearn/Ceshi/mmdetection$ python setup.py develop`
`  normalized_version,`
`running develop`
`running egg_info`
`writing mmdet.egg-info/PKG-INFO`
`writing dependency_links to mmdet.egg-info/dependency_links.txt`
`writing requirements to mmdet.egg-info/requires.txt`
 `writing top-level names to mmdet.egg-info/top_level.txt`
`reading manifest file 'mmdet.egg-info/SOURCES.txt'`
`writing manifest file 'mmdet.egg-info/SOURCES.txt'`
`running build_ext`
`copying build/lib.linux-x86_64-3.7/mmdet/ops/nms/soft_nms_cpu.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/nms`
`copying build/lib.linux-x86_64-3.7/mmdet/ops/nms/nms_cpu.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/nms`
`copying build/lib.linux-x86_64-3.7/mmdet/ops/nms/nms_cuda.cpython-37m-x86_64-linux gnu.so -> mmdet/ops/nms`
`copying build/lib.linux-x86_64-3.7/mmdet/ops/roi_align/roi_align_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/roi_align`
`copying build/lib.linux-x86_64-3.7/mmdet/ops/roi_pool/roi_pool_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/roi_pool`
`copying build/lib.linux-x86_64-3.7/mmdet/ops/dcn/deform_conv_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/dcn`
`copying build/lib.linux-x86_64-3.7/mmdet/ops/dcn/deform_pool_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/dcn`
`copying build/lib.linux-x86_64-3.7/mmdet/ops/sigmoid_focal_loss/sigmoid_focal_loss_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/sigmoid_focal_loss`
`copying build/lib.linux-x86_64-3.7/mmdet/ops/masked_conv/masked_conv2d_cuda.cpython-37m-x86_64-linux-gnu.so -> mmdet/ops/masked_conv`
`Creating /home/liukaixuan/D/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet.egg-link (link to .)`
`mmdet 1.0rc0+unknown is already the active version in _easy-install.pth`

There were not python3.7 in "classifiers"  of the function  "main()" of setup.py. Whether should i create a environment for py3.6 instead of py3.7?

**Comment by ljc199504** [comment]
you can have a try, i didn't run test_nms.py before, i just runned mask rcnn model and met with the issue as top of layers, so i don't have an idea whether version of python causes that in test_nms.py.(i use cuda10.0, pytorch 1.1 python 3.7.4 for training models, there is no error alerted)

**Comment by arcsinx11** [comment]
> you can have a try, i didn't run test_nms.py before, i just runned mask rcnn model and met with the issue as top of layers, so i don't have an idea whether version of python causes that in test_nms.py.(i use cuda10.0, pytorch 1.1 python 3.7.4 for training models, there is no error alerted)

Tanks for your help! Your reply is really fast.I solved the problem.According the traceback ,i deleted the ./local/share/Trash/files/mmdetection/.I redownloaded the git of mmdetection.Then i runned "python setup.py develop ",and runned  test_nms.py(gpu).It works! (i use cuda10.0, pytorch 1.1,python 3.7.3 ,gcc/g++ 7.3)

**Comment by hellock** [comment]
@teddybear0212 Mostly caused by the environment. You may update to the latest version, remove the original build directory, rebuild it, and then run `python tools/collect_env.py` to collect some environment information for trouble shooting.
