### ISSUE TITLE
RuntimeError: CUDA error: out of memory，but there are enough memory

### ISSUE THREAD

**Issue by mofang2016** [open-mmlab/mmdetection#1788]
This is our memory, I want to utilize the remaining three GPUs：
![image](https://user-images.githubusercontent.com/24251325/70524799-ec278c00-1b80-11ea-9025-44024a1a6435.png)
our train_model.sh as follow：
![image](https://user-images.githubusercontent.com/24251325/70525114-8d164700-1b81-11ea-9449-619aa7ee2783.png)
### The train.py is:
from __future__ import division
import argparse
import os

import torch
from mmcv import Config

from mmdet import __version__
from mmdet.apis import (get_root_logger, init_dist, set_random_seed,
                        train_detector)
from mmdet.datasets import build_dataset
from mmdet.models import build_detector

def parse_args():
    parser = argparse.ArgumentParser(description='Train a detector')
    parser.add_argument('config', help='train config file path')
    parser.add_argument('--work_dir', help='the dir to save logs and models')
    parser.add_argument(
        '--resume_from', help='the checkpoint file to resume from')
    parser.add_argument(
        '--validate',
        action='store_true',
        help='whether to evaluate the checkpoint during training')
    parser.add_argument(
        '--gpus',
        type=int,
        default=1,
        help='number of gpus to use '
        '(only applicable to non-distributed training)')
    parser.add_argument('--seed', type=int, default=None, help='random seed')
    parser.add_argument(
        '--launcher',
        choices=['none', 'pytorch', 'slurm', 'mpi'],
        default='none',
        help='job launcher')
    parser.add_argument('--local_rank', type=int, default=0)
    parser.add_argument(
        '--autoscale-lr',
        action='store_true',
        help='automatically scale lr with the number of gpus')

    args = parser.parse_args()
    # device = torch_utils.select_device(args.device, apex=mixed_precision)
    if 'LOCAL_RANK' not in os.environ:
        os.environ['LOCAL_RANK'] = str(args.local_rank)

    return args

def main():
    args = parse_args()

    cfg = Config.fromfile(args.config)
    # set cudnn_benchmark
    if cfg.get('cudnn_benchmark', False):
        torch.backends.cudnn.benchmark = True
    # update configs according to CLI args
    if args.work_dir is not None:
        cfg.work_dir = args.work_dir
    if args.resume_from is not None:
        cfg.resume_from = args.resume_from
    cfg.gpus = args.gpus

    if args.autoscale_lr:
        # apply the linear scaling rule (https://arxiv.org/abs/1706.02677)
        cfg.optimizer['lr'] = cfg.optimizer['lr'] * cfg.gpus / 8

    # init distributed env first, since logger depends on the dist info.
    if args.launcher == 'none':
        distributed = False
    else:
        distributed = True
        init_dist(args.launcher, **cfg.dist_params)

    # init logger before other steps
    logger = get_root_logger(cfg.log_level)
    logger.info('Distributed training: {}'.format(distributed))

    # set random seeds
    if args.seed is not None:
        logger.info('Set random seed to {}'.format(args.seed))
        set_random_seed(args.seed)

    model = build_detector(
        cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)

    datasets = [build_dataset(cfg.data.train)]
    if len(cfg.workflow) == 2:
        datasets.append(build_dataset(cfg.data.val))
    if cfg.checkpoint_config is not None:
        # save mmdet version, config file content and class names in
        # checkpoints as meta data
        cfg.checkpoint_config.meta = dict(
            mmdet_version=__version__,
            config=cfg.text,
            CLASSES=datasets[0].CLASSES)
    # add an attribute for visualization convenience
    model.CLASSES = datasets[0].CLASSES
    train_detector(
        model,
        datasets,
        cfg,
        distributed=distributed,
        validate=args.validate,
        logger=logger)

if __name__ == '__main__':
    main()

### How can I use the remaining GPUs or select a few fixed GPUs

**Comment by hellock** [comment]
Please follow the `Error report` issue template to report errors or potential bugs.

**Comment by mofang2016** [comment]
This is the error message:
![image](https://user-images.githubusercontent.com/24251325/70582853-de145280-1bf6-11ea-8005-ea3da141dd91.png)

**Comment by mofang2016** [comment]
I have solved the problem, thanks.

**Comment by gaussiangit** [comment]
@mofang2016 How ?

**Comment by mofang2016** [comment]
I have modified train_model.sh as follows
![图片](https://user-images.githubusercontent.com/24251325/70727963-892e2480-1d3b-11ea-975b-e72f12d2ff79.png)

**Comment by mofang2016** [comment]
> 
> 
> @mofang2016 How ?
I have modified train_model.sh as follows
![图片](https://user-images.githubusercontent.com/24251325/70728210-f346c980-1d3b-11ea-8c43-cb4f9d611bf7.png)
