### ISSUE TITLE
RuntimeError: CUDA error: invalid device function 

### ISSUE THREAD

**Issue by EasonEdison** [open-mmlab/mmdetection#1804]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
when I run as [demo](https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb),
in     **inds = nms_cuda.nms(dets_th, iou_thr)**
report an error:RuntimeError: CUDA error: invalid device function 

**Reproduction**
1. What command or script did you run?
```
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv
import torch
import os

config_file = 'configs/retinanet_r50_fpn_1x.py'
checkpoint_file = 'checkpoints/retinanet_r50_fpn_1x_20181125-7b0c2548.pth'

model = init_detector(config_file, checkpoint_file,device='cuda:0')
img = 'car.jpg'

result = inference_detector(model, img)
show_result_pyplot(img, result, model.CLASSES)
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
I don't change any thing
3. What dataset did you use?
I test a picture

**Environment**
 - OS: [Ubuntu 16.04.12]
 - GCC [5.4.0]
 - PyTorch version [1.3.1]
- How you installed PyTorch [pip]
- GPU model [2080Ti]
- CUDA 10.0.130 and CUDNN 7.6.4

**Error traceback**

```
  File "/home/ql-b423/Desktop/TXH/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 55, in nms
    inds = nms_cuda.nms(dets_th, iou_thr)
RuntimeError: CUDA error: invalid device function (launch_kernel at /opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/ATen/native/cuda/Loops.cuh:102)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7fe202790687 in /home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: void at::native::gpu_index_kernel<__nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>), &(void at::native::index_kernel_impl<at::native::OpaqueType<8> >(at::TensorIterator&, c10::ArrayRef<long>, c10::ArrayRef<long>)), 1u>> const&) + 0x78d (0x7fe2097f091d in /home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x53b70c2 (0x7fe2097ea0c2 in /home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x53b7578 (0x7fe2097ea578 in /home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x16150db (0x7fe205a480db in /home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #5: at::native::index(at::Tensor const&, c10::ArrayRef<at::Tensor>) + 0x44e (0x7fe205a42f0e in /home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #6: <unknown function> + 0x1b0c5aa (0x7fe205f3f5aa in /home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #7: <unknown function> + 0x35e67bd (0x7fe207a197bd in /home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #8: at::Tensor::index(c10::ArrayRef<at::Tensor>) const + 0xbb (0x7fe2076e054b in /home/ql-b423/anaconda3/envs/Kiruto/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #9: nms_cuda(at::Tensor, float) + 0x7e2 (0x7fe1a81feb2b in /home/ql-b423/Desktop/TXH/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #10: nms(at::Tensor const&, float) + 0x318 (0x7fe1a81ed6b8 in /home/ql-b423/Desktop/TXH/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x42c7d (0x7fe1a81fcc7d in /home/ql-b423/Desktop/TXH/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0x3fa01 (0x7fe1a81f9a01 in /home/ql-b423/Desktop/TXH/mmdetection/mmdet/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so)
frame #13: _PyCFunction_FastCallDict + 0x154 (0x55604e8c5c54 in /home/ql-b423/anaconda3/envs/Kiruto/bin/python)
frame #14: <unknown function> + 0x199abc (0x55604e94dabc in /home/ql-b423/anaconda3/envs/Kiruto/bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x30a (0x55604e97075a in /home/ql-b423/anaconda3/envs/Kiruto/bin/python)
frame #16: PyEval_EvalCodeEx + 0x329 (0x55604e9489b9 in /home/ql-b423/anaconda3/envs/Kiruto/bin/python)
frame #17: <unknown function> + 0x1958e6 (0x55604e9498e6 in /home/ql-b423/anaconda3/envs/Kiruto/bin/python)
frame #18: PyObject_Call + 0x3e (0x55604e8c5a5e in /home/ql-b423/anaconda3/envs/Kiruto/bin/python)

```

**Comment by ZwwWayne** [comment]
Hi @EasonEdison ,
This is related to your environment. How you install your Pytorch? Is your pytorch consistent with your CUDA environment?

**Comment by hristo-vrigazov** [comment]
Getting the exact same error. The error happens inside `nms`, but can't tell what would be the reason. Using the latest pytorch with cudnn 10.1 - every other project seems to work. Maybe we should try downgrading?

**Comment by wuhy08** [comment]
I am getting the same error on my new machine.

**Comment by EasonEdison** [comment]
> Hi @EasonEdison ,
> This is related to your environment. How you install your Pytorch? Is your pytorch consistent with your CUDA environment?

I use conda install Pytorch 
conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
Is that wrong？

**Comment by EasonEdison** [comment]
> Getting the exact same error. The error happens inside `nms`, but can't tell what would be the reason. Using the latest pytorch with cudnn 10.1 - every other project seems to work. Maybe we should try downgrading?

I'm trying to do that

**Comment by hellock** [comment]
I have been working with mmdet and CUDA 10.1 for a long time, and your problem looks like an environment issue. You may update to the latest version and rebuild mmdetection, then run `python tools/collect_env.py` to check the environments.

**Comment by EasonEdison** [comment]
> I have been working with mmdet and CUDA 10.1 for a long time, and your problem looks like an environment issue. You may update to the latest version and rebuild mmdetection, then run `python tools/collect_env.py` to check the environments.

yes , after reinstall cuda and rebuild mmdetection , it works , thank you.
