### ISSUE TITLE
Error when running the demo

### ISSUE THREAD

**Issue by yestinchen** [open-mmlab/mmdetection#2008]
Hi, 

I setup the environment and try to run the demo (with exact the same code from `inference_demo.ipynb`) from a single file. However, I got the following error:

```
THCudaCheck FAIL file=mmdet/ops/roi_align/src/roi_align_kernel.cu line=140 error=98 : unrecognized error code
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    result = inference_detector(model, img)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/apis/inference.py", line 86, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/home/ytchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/models/detectors/base.py", line 140, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/models/detectors/base.py", line 123, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/models/detectors/two_stage.py", line 308, in simple_test
    x, img_meta, proposal_list, self.test_cfg.rcnn, rescale=rescale)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/models/detectors/test_mixins.py", line 106, in simple_test_bboxes
    x[:len(self.bbox_roi_extractor.featmap_strides)], rois)
  File "/home/ytchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/models/roi_extractors/single_level.py", line 105, in forward
    roi_feats_t = self.roi_layers[i](feats[i], rois_)
  File "/home/ytchen/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/ops/roi_align/roi_align.py", line 80, in forward
    self.sample_num)
  File "/home/ytchen/workspace/git/mmdetection/mmdet/ops/roi_align/roi_align.py", line 26, in forward
    sample_num, output)
RuntimeError: cuda runtime error (98) : unrecognized error code at mmdet/ops/roi_align/src/roi_align_kernel.cu:140
[1]    18889 segmentation fault (core dumped)  python test.py
```

**Environment**
I am using conda and here's the output produced by `python tools/collect_env.py`.
```
sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda-10.0
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GPU 0: GeForce GTX 1070
GCC: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.5.0
OpenCV: 4.1.2
MMCV: 0.2.16
MMDetection: 1.0rc1+bb0b2fe
MMDetection Compiler: GCC 7.4
MMDetection CUDA Compiler: 10.0
```

Any ideas what is going on? Thanks!

**Comment by yestinchen** [comment]
I figured it out. This is because I installed `cudatoolkit10.1` first, and then downgrade that to the `10.0` version. However, I didn't clean the mmdet build files.

This is solved by deleting the build folder and all `*.so` files, followed by a rebuild through command `pip install -e .`.

I think you may want to add this in the `install.md` as a general troubleshooting instruction. 
Thanks anyway!
