### ISSUE TITLE
About category_id when creating my own COCO-style dataset

### ISSUE THREAD

**Issue by KaiChen1998** [open-mmlab/mmdetection#2047]
When you make your own dataset to train a detection model (e.g. Mask RCNN), the category_id range is **[0, 79]** or **[1, 80]** (letting 0 for background)?

Since first I use [0, 79] the model works fine. However when I notice the problem and change to [1, 80], it reports the error in the following and I think it's because illegal class index.

```
RuntimeError: CUDA error: device-side assert triggered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /opt/conda/conda-bld/pytorch_1565287025495/work/c10/cuda/CUDACachingAllocator.cpp:569)
```

**Comment by ZwwWayne** [comment]
For now, the cat_id is in [1, 80] if you use the coco dataset, where 0 indicates the background. You might need to also check the num_classes of your bbox head. It seems to be some inconsistency about the cat_ids in your modification from your error.

**Comment by KaiChen1998** [comment]
@ZwwWayne Thank you for your reply. I wrongly encoded the background in the dataset json file explicitly.

**Comment by ZwwWayne** [comment]
The issue is closed because the problem seems to be solved. Feel free to reopen it if you have any further questions.

**Comment by KaiChen1998** [comment]
@ZwwWayne Hi, here is another question about fine tuning. Is there an easy way to fix the parameters of parts of the network (e.g. fix the backbone and RPN and only train detection head when fine tuning a Mask RCNN model) in a config file? Thank you!
