### ISSUE TITLE
cuda runtime error (209) : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by madiltalay** [open-mmlab/mmdetection#2606]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
>RuntimeError                              Traceback (most recent call last)
<ipython-input-23-9392f7469087> in <module>()
----> 1 train_detector(model, datasets, cfg, distributed=distributed, validate=validate, timestamp=timestamp, meta=meta)
17 frames
/content/gdrive/My Drive/Developer/Repositories/mmdetection/mmdet/ops/sigmoid_focal_loss/sigmoid_focal_loss.py in forward(ctx, input, target, gamma, alpha)
     17 
     18         loss = sigmoid_focal_loss_ext.forward(input, target, num_classes,
---> 19                                               gamma, alpha)
     20         return loss
     21 

>RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at mmdet/ops/sigmoid_focal_loss/src/cuda/sigmoid_focal_loss_cuda.cu:128

**Reproduction**
```
train_detector(model, datasets, cfg, distributed=distributed, validate=validate, timestamp=timestamp, meta=meta)
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Just added a new dataset in the config.

3. What dataset did you use?
I am using a custom dataset, similar to PASCAL VOC format.

**Environment**

1. Please run `python mmdet/utils/collect_env.py` to collect necessary environment infomation and paste it here.

sys.platform: linux
Python: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: Tesla K80
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.5.0+cu101
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_INTERNAL_THREADPOOL_IMPL -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.6.0+cu101
OpenCV: 4.2.0
MMCV: 0.5.0
MMDetection: 2.0.0+5a0e55a
MMDetection Compiler: GCC 7.5
MMDetection CUDA Compiler: 10.1

2. You may add addition that may be helpful for locating the problem:
I am using Google Colab with the default environment

**Error traceback**
I am wondering if the error arises from the following. When I look at the /usr/local/ directory, I find three folders named: (a) cuda, (b) cuda-10.0, (c) cuda-10.1
Looking into each of them, there exist a /bin/nvcc directory in each.
Could these multiple versions of cuda be the source of error?
If so, how do I fix it?

**Bug fix**

**Comment by hellock** [comment]
https://github.com/pytorch/pytorch/issues/31285

**Comment by madiltalay** [comment]
I think the issue is probably with _focal loss_, as the error also suggests:

> RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at mmdet/ops/sigmoid_focal_loss/src/cuda/sigmoid_focal_loss_cuda.cu:128

Because when I change the model from retinanet to ssd, it works good

**Comment by hellock** [comment]
It's because your GPU is too old and not supported by the latest pytorch. You may refer to the issue above.

**Comment by naveenggmu** [comment]
@hellock By saying "GPU is too old", do you mean the cuda version running on the gpu? But I was able to run detectron2 with the same gpu ( pytorch 1.5, cuda 10.1).

**Comment by naveenggmu** [comment]
@madiltalay Downgrade pytorch to 1.4 and it will work !!

**Comment by naveenggmu** [comment]
This might sound completely useless but try removing build and running setup.py.
It worked for me.
