### ISSUE TITLE
No output after some iteration, program stucks

### ISSUE THREAD

**Issue by hanjianhua44** [open-mmlab/mmdetection#3212]
I use mmdetection 2.2.0 and mmcv 0.6.2, the latest.

I train the mmdetection maskrcnn r50 using LVIS dataset, on 8 gpus, but when I set the batch size (samples per GPU ) to 1, the program stucks at the specific iteration(4300) on first epoch with no error message, after that there is no log output.

But if I change the batch size (samples per GPU ) to 2, it works and can train normaly.

Someone please help!

#2153 

I am using the latest version of mmdetection, but still it is showing error. And when i set find_unused_parameters = True, error disappears but training freezes.

**Comment by hanjianhua44** [comment]
#2153

**Comment by Wei-ucas** [comment]
#3563 
I met the same problem and I solved it, you can try it.

**Comment by hanjianhua44** [comment]
> #3563
> I met the same problem and I solved it, you can try it.

Thx!
