### ISSUE TITLE
CUDA OUT OF MEMORY

### ISSUE THREAD

**Issue by epsilon11101** [open-mmlab/mmdetection#3585]
Hi, I have the below problem 

RuntimeError: CUDA out of memory. Tried to allocate 6.96 GiB (GPU 0; 7.80 GiB total capacity; 721.23 MiB already allocated; 6.05 GiB free; 792.00 MiB reserved in total by PyTorch)

 I configure with a batch size of 1, and with other models, I never had these problems, I can found solution for this problems

**Comment by v-qjqs** [comment]
Hi, you may first check whether the GPU memory is released before your next run. Or you may try with FP16 training?

**Comment by hellock** [comment]
Maybe you used a large model and 8G is not enough.

**Comment by epsilon11101** [comment]
I solved it thanks 👍

**Comment by WuChannn** [comment]
@epsilon11101 hello, I met with the same problem, how do you solve it? thanks

**Comment by epsilon11101** [comment]
hi @WuChannn I just  resize images to a smaller size
