### ISSUE TITLE
How can I run 2 models on one server?

### ISSUE THREAD

**Issue by Luodian** [open-mmlab/mmdetection#361]
I am trying to run two models both on our server, but I encountered one NCCL error. Both of them are launched by  script `dist_train.sh`.

Detail info is as follows:
`Traceback (most recent call last):
  File "./tools/train.py", line 90, in <module>
    main()
  File "./tools/train.py", line 86, in main
    logger=logger)
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.6rc0+85c30cc-py3.5.egg/mmdet/apis/train.py", line 57, in train_detector
    _dist_train(model, dataset, cfg, validate=validate)
  File "/usr/local/lib/python3.5/dist-packages/mmdet-0.6rc0+85c30cc-py3.5.egg/mmdet/apis/train.py", line 72, in _dist_train
    model = MMDistributedDataParallel(model.cuda())
  File "/usr/local/lib/python3.5/dist-packages/mmcv-0.2.4-py3.5.egg/mmcv/parallel/distributed.py", line 20, in __init__
    self._sync_params()
  File "/usr/local/lib/python3.5/dist-packages/mmcv-0.2.4-py3.5.egg/mmcv/parallel/distributed.py", line 34, in _sync_params
    self.broadcast_bucket_size)
  File "/usr/local/lib/python3.5/dist-packages/mmcv-0.2.4-py3.5.egg/mmcv/parallel/distributed.py", line 25, in _dist_broadcast_coalesced
    dist.broadcast(flat_tensors, 0)
  File "/usr/local/lib/python3.5/dist-packages/torch/distributed/distributed_c10d.py", line 737, in broadcast
    work = _default_pg.broadcast([tensor], opts)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:260, unhandled system error
`

**Comment by hellock** [comment]
Maybe related to #261

**Comment by harryhan618** [comment]
`CUDA_VISIBLE_DEVICES=4,5,6,7 PORT=29501 ./tools/dist_train.sh ${CONFIG_FILE} 4` from [getting_started.md](https://github.com/open-mmlab/mmdetection/blob/master/docs/getting_started.md)

**Comment by hongrui16** [comment]
@harryhan618  
u are correct. I solved the problem after changing port number every time.
