### ISSUE TITLE
Memory cost when using own backbone.

### ISSUE THREAD

**Issue by Yuyn1234** [open-mmlab/mmdetection#3646]
I used my own backbone which was pre-trained on ImageNet with DataParallel (not DistributedDataParallel). And I just replace ResNet with my own backbone without any other changes about the codes. At the stage of data loading, GPU 0 processes 8 courses at the same time and it leads to out of memory when loading model. I think these 8 courses should be equally distributed to 8 GPUs. And it is true when I use ResNet provided by pytorch official. I do not know why does this happen to my backbone. I use 8 2080Ti GPUs. Normally, the memory is sufficient.

**Comment by ZwwWayne** [comment]
Hi @Yuyn1234 ,
This might because the backbone you trained are dumped as GPU tensors thus could cause GPU memory when loading them because they all need to be loaded to GPU0 first. You could use tools like [publish_model.py](https://github.com/open-mmlab/mmdetection/blob/master/tools/publish_model.py) to convert the weights in the checkpoints to CPU Tensors first and then use them for training.

**Comment by Yuyn1234** [comment]
Thanks, I have fixed this problem with your solution.
