### ISSUE TITLE
I got "RuntimeError: CUDA error: invalid device function" when try to run test

### ISSUE THREAD

**Issue by ArchNew** [open-mmlab/mmdetection#4012]
I found an old post with the same issue, but its solution can't solve my problem. Below is the information after I run collect_env.py:
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: TITAN Xp
CUDA_HOME: /home/tujun/.local/cuda-10.2
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits-Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.1.5
MMCV Compiler: GCC 6.3
MMCV CUDA Compiler: 9.2
MMDetection: 2.5.0+9caa197

**Comment by RyanXLi** [comment]
I think the problem is that your CUDA version is different everywhere. Your MMCV is compiled with CUDA 9.2. Your PyTorch is built with CUDA 10.1. And your current CUDA runtime and NVCC are 10.2. I would suggest reinstalling PyTorch and mmcv with CUDA 10.2.

**Comment by ArchNew** [comment]
> I think the problem is that your CUDA version is different everywhere. Your MMCV is compiled with CUDA 9.2. Your PyTorch is built with CUDA 10.1. And your current CUDA runtime and NVCC are 10.2. I would suggest reinstalling PyTorch and mmcv with CUDA 10.2.

Thanks! I solved my problem according to your suggestion.

Some experience to share:
Must match all pre-built tools' cuda version. PyTorch pre-built version is compiled with cuda 10.1, even you install PyTorch via conda with option "cudatoolkit==10.2", it only means the anaconda will install cudatoolkit 10.2 support, not with a PyTorch pre-built on cuda 10.2. We can run collect_env.py to varify this.

Don't install MMCV with "pip install mmcv-full", it will install a version with cuda 9.2. If you want to install mmcv with cuda 10.1, you must compile it yourself.
