### ISSUE TITLE
DetectoRS on custom dataset - RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by borgarpa** [open-mmlab/mmdetection#4246]
**Environment**

OS: Linux Google Colab runtime
MMCV version: 1.2.1
MMDet version: 2.7.0
PyTorch version: 1.6.0+cu101
	- Available CUDA device: True
	- CUDA version: 10.1
Compiler version: GCC 7.3

**Problem description**
I created a custom COCO-like dataset with only one class and a grey scale mask images consisting of only background in black and classes in grey (only one grey tone, since there is just one class). I was planning to use them in order to train a DetectoRS model, but I keep bumping into errors. I run the following in order to get a proper traceback message: `CUDA_LAUNCH_BLOCKING=1 python3 ./DetectoRS_script.py`

As a result I get:
[DetectoRS_issue.txt](https://github.com/open-mmlab/mmdetection/files/5655237/DetectoRS_issue.txt)

**Code**
The configs and code are as follows:
[DetectoRS_script.txt](https://github.com/open-mmlab/mmdetection/files/5655271/DetectoRS_script.txt)
[Configs.txt](https://github.com/open-mmlab/mmdetection/files/5655278/Configs.txt)

The classes I used are `('log',)`, and the `semantic_head` number of classes is set to `num_classes=2`, so that it takes into account background pixels (black) and foreground (grey). The rest are set to `num_classes=1`.

**Possible cause**
I was wondering if JPEG format causes images to lose quality, hence adding noise (pixel values different from 0 or class color). However, the model keeps asking for masks to be the same format as training images are, which is weird, since COCO dataset uses JPEG format for training images and PNG format for segmentation masks. Doing it that way causes a traceback because training images and masks are not named equally. 

If that wasn't the case, what might be causing this error?

Thanks in advance!

**Comment by ZwwWayne** [comment]
The real bug trace is the following line
```
/pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [992,0,0] Assertion `t >= 0 && t < n_classes` failed.
```
This means that the label is greater than the num_classes you set in the head. For example, the semantic label or gt labels ranges from 0-100, but your num_classes is still 80. You can try modify num_classes to the correct value to avoid this bug.

**Comment by borgarpa** [comment]
> The real bug trace is the following line
> 
> ```
> /pytorch/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [992,0,0] Assertion `t >= 0 && t < n_classes` failed.
> ```
> 
> This means that the label is greater than the num_classes you set in the head. For example, the semantic label or gt labels ranges from 0-100, but your num_classes is still 80. You can try modify num_classes to the correct value to avoid this bug.

Thank you for your quick answer! 

I will try modifying `num_classes` directly from the config file instead of the script, which was sort of a sloppy job. I will modify the dataset class too so that I have more control over the process of customization.

However, I would also like to know if I can use masks as PNG files and images as JPEG files. That would eliminate part of the problem, since I already found that segmentation masks are noisy when saved as JPEG, hence adding more than just two classes (BG and logs). If could feed the model with PNG masks that problem would disappear, since PNG is a lossless format.

Cheers!

**Comment by ZwwWayne** [comment]
Then I have no idea, I think you could try.

**Comment by borgarpa** [comment]
I figured it out for PNG vs JPEG format. It seems like some caps in the images filename extension were confusing the model a bit... Totally my fault, but I just fixed it using lowercase for the whole image name.

However, the problem persists even when using PNG images with just two colors in them. Am I making a logical mistake by assuming the segmentation mask only has two classes? I think having just one class and background pixels should result in two classes, but maybe I am wrong... Although, I also tried 1 and 3 classes and it didn't work either.

I'm absolutely certain the dataset is right (at least images and COCO annotations, don't know about masks), since I trained a Mask RCNN model and it worked fantastically (**great job by the way!**). But segmentation masks don't seem to be working so well for DetectoRS...

**Comment by ZwwWayne** [comment]
It seems that there are still some hard code about loading semantic masks with COCO-format data [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/coco.py#L170). I am not sure whether it is related, just FYI in case it helps. We will refine this part in the future.

**Comment by borgarpa** [comment]
Thanks for the info! I will stay tuned
