### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by haozhihang123** [open-mmlab/mmdetection#4798]
When I install the latest mmdetection, after the installation, the training model will report an error:RuntimeError: CUDA error: invalid device function.I tried several versions of mmcv, but none of them worked.
My environment is as follows:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.12.0                    <pip>
addict                    2.4.0                     <pip>
backcall                  0.2.0                     <pip>
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.1.19            h06a4308_1  
cachetools                4.2.1                     <pip>
certifi                   2020.12.5        py37h06a4308_0  
chardet                   4.0.0                     <pip>
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.10.0                    <pip>
Cython                    0.29.22                   <pip>
decorator                 4.4.2                     <pip>
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.10.4               h5ab3b9f_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.5             h71b1129_1002  
google-auth               1.28.0                    <pip>
google-auth-oauthlib      0.4.3                     <pip>
grpcio                    1.36.1                    <pip>
idna                      2.10                      <pip>
importlib-metadata        3.7.3                     <pip>
intel-openmp              2020.2                      254  
ipdb                      0.13.7                    <pip>
ipython                   7.21.0                    <pip>
ipython-genutils          0.2.0                     <pip>
jedi                      0.18.0                    <pip>
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.3.1                     <pip>
lame                      3.100                h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libiconv                  1.15                 h63c8f33_5  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.2.0                h3942068_0  
libuv                     1.40.0               h7b6447c_0  
libwebp-base              1.2.0                h27cfd23_0  
lz4-c                     1.9.3                h2531618_0  
Markdown                  3.3.4                     <pip>
matplotlib                3.3.4                     <pip>
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.3.0            py37h54f3939_0  
mkl_random                1.1.1            py37h0573a6f_0  
mmcv-full                 1.2.5                     <pip>
mmdet                     2.8.0                     <pip>
mmpycocotools             12.0.3                    <pip>
ncurses                   6.2                  he6710b0_1  
nettle                    3.4.1                hbb512f6_0  
ninja                     1.10.2           py37hff7bd54_0  
numpy                     1.19.2           py37h54aff64_0  
numpy-base                1.19.2           py37hfa32c7d_0  
oauthlib                  3.1.0                     <pip>
olefile                   0.46                       py_0  
opencv-python             4.5.1.48                  <pip>
openh264                  2.1.0                hd408876_0  
openssl                   1.1.1j               h27cfd23_0  
parso                     0.8.1                     <pip>
pexpect                   4.8.0                     <pip>
pickleshare               0.7.5                     <pip>
pillow                    8.1.2            py37he98fc37_0  
pip                       21.0.1           py37h06a4308_0  
prompt-toolkit            3.0.17                    <pip>
protobuf                  3.15.6                    <pip>
ptyprocess                0.7.0                     <pip>
pyasn1                    0.4.8                     <pip>
pyasn1-modules            0.2.8                     <pip>
Pygments                  2.8.1                     <pip>
pyparsing                 2.4.7                     <pip>
python                    3.7.10               hdb3f193_0  
python-dateutil           2.8.1                     <pip>
pytorch                   1.8.0           py3.7_cuda10.1_cudnn7.6.3_0    pytorch
PyYAML                    5.4.1                     <pip>
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                    <pip>
requests-oauthlib         1.3.0                     <pip>
rsa                       4.7.2                     <pip>
setuptools                52.0.0           py37h06a4308_0  
six                       1.15.0             pyhd3eb1b0_0  
sqlite                    3.35.1               hdfb4753_0  
tensorboard               2.4.1                     <pip>
tensorboard-plugin-wit    1.8.0                     <pip>
terminaltables            3.1.0                     <pip>
tk                        8.6.10               hbc83047_0  
toml                      0.10.2                    <pip>
torchvision               0.9.0                py37_cu101    pytorch
traitlets                 5.0.5                     <pip>
typing_extensions         3.7.4.3            pyha847dfd_0  
urllib3                   1.26.4                    <pip>
wcwidth                   0.2.5                     <pip>
Werkzeug                  1.0.1                     <pip>
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
yapf                      0.31.0                    <pip>
zipp                      3.4.1                     <pip>
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0

**Comment by ZwwWayne** [comment]
This usually means the CUDA version is incompatible with the CUDA version used for compiling MMCV.

**Comment by haozhihang123** [comment]
"conda install pytorch cudatoolkit=10.0 torchvision"
I solved this problem by installing this version of CUDA.
