### ISSUE TITLE
about distributed train, there would be several extra process which costs 751M each,  why is that?

### ISSUE THREAD

**Issue by wanzn** [open-mmlab/mmdetection#480]
![微信图片_20190410210746](https://user-images.githubusercontent.com/33977046/55881179-c3578d00-5bd4-11e9-821a-98eb5466aafe.png)

The dist_train worked fine before, suddenly those extra process came, and causes my 0 GPU out of memory if i try to train something big.

Any help?

**Comment by hellock** [comment]
What scripts or commands did you run?

**Comment by wanzn** [comment]
> What scripts or commands did you run?
dist_train.sh
#!/usr/bin/env bash
PYTHON=${PYTHON:-"python"}
export NGPUS=4
CUDA_VISIBLE_DEVICES=0,1,2,3 $PYTHON -m torch.distributed.launch --nproc_per_node=$NGPUS --master_port 2400 tools/train.py configs/mask_rcnn_r101_fpn_gn_2x.py --gpus 4

and i changed "--launcher"  in train.py to default='pytorch'.

I ran the command:   ./tools/dist_train.sh

**Comment by RuiminChen** [comment]
when runing distribute training with custom backbones, I meet the same issue. 
I solved this problem through transforming my pretrained model state_dict from gpu to cpu. Maybe you could have a try.
This function https://github.com/open-mmlab/mmcv/blob/c728193f8d1dc62537c54b29748d9ba595184d40/mmcv/runner/checkpoint.py#L143
should help you.

**Comment by RuiminChen** [comment]
when runing distribute training with custom backbones, I meet the same issue.
I solved this problem through transforming my pretrained model weights from gpu to cpu. Maybe you could have a try.
This function https://github.com/open-mmlab/mmcv/blob/c728193f8d1dc62537c54b29748d9ba595184d40/mmcv/runner/checkpoint.py#L143
should help you.

**Comment by jianghaojun** [comment]
I meet the same issue. The problem is caused by loading the pretrained model weight to gpu, you can set the map_location = 'cpu'  in load_checkpoint() function which is defined in mmcv/runner/checkpoint.py.

**Comment by jianghaojun** [comment]
I encountered the same issue. I solved it by setting the argument map_location='cpu' in mmcv/runner/checkpoint.py/load_checkpoint() function.
