### ISSUE TITLE
Cuda OOM when using multi-gpu training (MMDDP)

### ISSUE THREAD

**Issue by ginobilinie** [open-mmlab/mmdetection#5401]
Hi, I'm currently using mmdetection to train swin-transformer based instance segmentation model. I found it is fine to set the samples_per_gpu=3 when using single gpu training, but if I use multi-gpu training (dist_train.sh), even if I set the samples_per_gpu=1, there appears CUDA OOM issues.

Error info:
RuntimeError: CUDA out of memory. Tried to allocate 240.00 MiB (GPU 2; 10.76 GiB total capacity; 9.16 GiB already allocated; 205.69 MiB free; 9.65 GiB reserved in total by PyTorch)

Here is my environment:
gpu: nvidia 2080 TI
os: Ubuntu 18.04
cuda: 10.1
pytorch: 1.7.1
mmcv: 1.3.7
mmdet: 2.11.0

Can anyone helps? Thanks in advance.

**Comment by ginobilinie** [comment]
Any help? When I use single-gpu for training, the memory cost for one sample is around 3.4 gb(samples_per_gpu=1), while when I use multi-gpu for training, it goes to 6.7gb for each sample on each gpu (samples_per_gpu=1). 

I have experimented with another environment, but the problem is still there. 

Here is my new environment:
gpu: nvidia 2080 TI
os: Ubuntu 18.04
cuda: 10.2
pytorch: 1.5.0
mmcv: 1.3.7
mmdet: 2.11.0

**Comment by jshilong** [comment]
Any modification to the code?  Can you give me the script to reproduce the error?

**Comment by ginobilinie** [comment]
> the

Thanks. I have solved it myself. I changed the framework to panopticSeg, and the test pipeline caused the pipeline. Now I have modified the mmde/apis/test.py, it works fine now. Thanks very much.
