### ISSUE TITLE
im2col_step=cur_im2col_step)

### ISSUE THREAD

**Issue by MyCurveNet** [open-mmlab/mmdetection#5406]
**Describe the bug**
When i run configs/dcn/cascade_mask_rcnn_x101_32x4d_fpn_dconv_c3-c5_1x_coco.py, it will cause a error as following
Traceback (most recent call last):
  File "tools/train.py", line 188, in <module>
    main()
  File "tools/train.py", line 184, in main
    meta=meta)
  File "/home1/jiangwenj02/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home1/jiangwenj02/mmdetection/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home1/jiangwenj02/mmdetection/mmdet/models/detectors/base.py", line 171, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home1/jiangwenj02/mmdetection/mmdet/models/detectors/two_stage.py", line 126, in forward_train
    x = self.extract_feat(img)
  File "/home1/jiangwenj02/mmdetection/mmdet/models/detectors/two_stage.py", line 66, in extract_feat
    x = self.backbone(img)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/jiangwenj02/mmdetection/mmdet/models/backbones/resnet.py", line 642, in forward
    x = res_layer(x)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/jiangwenj02/mmdetection/mmdet/models/backbones/resnet.py", line 297, in forward
    out = _inner_forward(x)
  File "/home1/jiangwenj02/mmdetection/mmdet/models/backbones/resnet.py", line 274, in _inner_forward
    out = self.conv2(out)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/mmcv/ops/deform_conv.py", line 364, in forward
    self.dilation, self.groups, self.deform_groups)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/mmcv/ops/deform_conv.py", line 109, in forward
    im2col_step=cur_im2col_step)
RuntimeError: CUDA error: invalid device function
[1]    21284 segmentation fault (core dumped)  python tools/train.py  --gpu-ids 1

**Reproduction**

1. What command or script did you run?

python tools/train.py configs/dcn/cascade_mask_rcnn_x101_32x4d_fpn_dconv_c3-c5_1x_coco.py --gpu-ids 1

2. Did you make any modifications on the code or config? Did you understand what you have modified?

i dont make any modifications.

3. What dataset did you use?

I train it on COCO

**Environment**

------------------------------------------------------------
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0
OpenCV: 4.5.2
MMCV: 1.3.7
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.0
MMDetection: 2.13.0+ec8a3b0
------------------------------------------------------------

**Error traceback**
If applicable, paste the error trackback here.

  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/mmcv/ops/deform_conv.py", line 364, in forward
    self.dilation, self.groups, self.deform_groups)
  File "/home/user/anaconda3/envs/mmtrack/lib/python3.7/site-packages/mmcv/ops/deform_conv.py", line 109, in forward
    im2col_step=cur_im2col_step)
RuntimeError: CUDA error: invalid device function

**Comment by BIGWangYuDong** [comment]
This error seems that your CUDA version does not match the Pytorch version. Please refer to [Pytorch](https://pytorch.org/get-started/previous-versions/).

**Comment by jiangwenj02** [comment]
thank you. i change the version of mmcv and cuda to 10.1, and it solves the problem.

**Comment by AnRanbel** [comment]
> thank you. i change the version of mmcv and cuda to 10.1, and it solves the problem.

I have the same problem. May I ask what version of mmcv and pytorch you have.
