### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by LIUZIJING-CHN** [open-mmlab/mmdetection#5449]
The problem I meet is that: 

During the training, the occupation of cuda is around 5.6G which is acceptable. But in testing phase, the occupation increases sharply and stops at the 208th testing of 3079 images in total.

I use my own dataset in coco format, and follow the setting of `_'faster_rcnn_r50_fpn_1x_coco.py'_,` with only changing the class number, no other difference.

```
[>>>>>                                             ] 308/3079, 31.0 task/s, elapsed: 10s, ETA:    89sTraceback (most recent call last):
  File "tools/train.py", line 187, in <module>
    main()
  File "tools/train.py", line 183, in main
    meta=meta)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/core/evaluation/eval_hooks.py", line 146, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/apis/test.py", line 27, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/detectors/base.py", line 183, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/detectors/base.py", line 160, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/detectors/two_stage.py", line 197, in simple_test
    _x, x = self.extract_feat(img)  #for visualization
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/detectors/two_stage.py", line 85, in extract_feat
    x = self.neck(x)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/mmdet-2.11.0-py3.7.egg/mmdet/models/necks/fpn.py", line 198, in forward
    laterals[i], size=prev_shape, **self.upsample_cfg)
  File "/home/jude/.conda/envs/class/lib/python3.7/site-packages/torch/nn/functional.py", line 3690, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 10.91 GiB total capacity; 8.75 GiB already allocated; 9.75 MiB free; 9.57 GiB reserved in total by PyTorch)
```

**Comment by LIUZIJING-CHN** [comment]
In fact, it's the problem in validation phase. I have not test the model since none checkpoint file has been produced, for no training epoch has been finished.

**Comment by ElectronicElephant** [comment]
Can you check whether the input resolution between training and testing process is the same?

**Comment by LIUZIJING-CHN** [comment]
> Can you check whether the input resolution between training and testing process is the same?

yes, the input resolution for validation and training set are the same for (1333, 800)

**Comment by LIUZIJING-CHN** [comment]
Fine, I have solved the problem by renewing the version of mmdetection, maybe it was caused by the mismatch of mmcv and mmdetection.
