### ISSUE TITLE
CUDA out of memory 

### ISSUE THREAD

**Issue by alaa-shubbak** [open-mmlab/mmdetection#5889]
Dear All , 

I have a question reagrd the problem of CUDA out of the memory. 

I try to train a CentriapetalNet on my custom dataset , which has the same format of COCO dataset. 
this is the config file : https://github.com/open-mmlab/mmdetection/tree/master/configs/centripetalnet
I got such error massage on CUDA memory ,  I changed the  following code 
from 6*3 to 16*4 

```
data = dict(
    samples_per_gpu=6,
    workers_per_gpu=3,
```
I noticed that changing such batch size help in reduce the CUDA memory needs during the training. 
but it is still not working , I did not understand the theory behind . also  I really confused what should I do to continues the training. 

I read this document : 
https://mmdetection.readthedocs.io/en/latest/faq.html , the part of CUDA memory

and i did not know how to change those three items described there. 

any help will be highly appreciated.  

![cuda out of memory](https://user-images.githubusercontent.com/10245810/129450800-b52d63ee-05c7-4b4d-9a11-78803c0a96cb.JPG)

**Comment by collinzrj** [comment]
Hi, what do you mean by "I changed the following code from 63 to 164"
Did you changed
```
data = dict(
    samples_per_gpu=6,
    workers_per_gpu=3,
```
to the following code?
```
data = dict(
    samples_per_gpu=16,
    workers_per_gpu=4,
```

**Comment by alaa-shubbak** [comment]
> Hi, what do you mean by "I changed the following code from 63 to 164"
> Did you changed
> 
> ```
> data = dict(
>     samples_per_gpu=6,
>     workers_per_gpu=3,
> ```
> 
> to the following code?
> 
> ```
> data = dict(
>     samples_per_gpu=16,
>     workers_per_gpu=4,
> ```

@collinzrj 
yes exactly

**Comment by collinzrj** [comment]
Did the first work for you? the change of  `samples_per_gpu` from 6 to 16 should increase the memory usage but not decrease.

**Comment by alaa-shubbak** [comment]
It does not work , it still shows an error massage of CUDA out memory , but the presented massage shows that I need to allocate less memory ...first case gave me a massage to allocate around 115 MiB . Now it gives me only 64MiB .. that makes me said that it reduce the memory , but I still have such problem, and I don't  know how to fix it.

**Comment by collinzrj** [comment]
The memory tried to allocate here is not the total amount of memory allocated, so the reduction from 115MiB to 64 MiB may not mean the memory usage is smaller. What about trying to set the samples_per_gpu to be 1?

**Comment by collinzrj** [comment]
> It does not work , it still shows an error massage of CUDA out memory , but the presented massage shows that I need to allocate less memory ...first case gave me a massage to allocate around 115 MiB . Now it gives me only 64MiB .. that makes me said that it reduce the memory , but I still have such problem, and I don't know how to fix it.

I have tested on my computer which also has a 8GB gpu like yours, and it seems that `samples_per_gpu` equal or below **2** works, greater than 2 will produce OOM.

**Comment by alaa-shubbak** [comment]
Hello , thank you for replaying

I reduced the  samples_per_gpu to 1 as bellow 

![centraipetalnet](https://user-images.githubusercontent.com/10245810/129598628-1ec4f329-e415-48cc-9f6a-2bc1dfab727e.JPG)

but i still have the same problem as this 
![error message](https://user-images.githubusercontent.com/10245810/129598800-8d5c5ef8-3a2f-47ec-8cfe-e2f406268dee.JPG)

any suggestion ?

**Comment by collinzrj** [comment]
What's the size of your image? If the image is too big, there may also be OOM.

**Comment by alaa-shubbak** [comment]
the size of my images are : 
"width": 2208,
      "height": 1242,

**Comment by collinzrj** [comment]
> the size of my images are : 
> 
> "width": 2208,
> 
>       "height": 1242,

My image is of size 640*360, try resize your image

**Comment by alaa-shubbak** [comment]
any idea or functions that used to resize images , please?

**Comment by collinzrj** [comment]
scikit-image and pillow has resize functions, or if you have a small dataset, you can resize the images manually (by photo editor software) to make it work at first.

**Comment by alaa-shubbak** [comment]
but there is no way to do so inside the mmdetection library  , a function or something like that?

**Comment by collinzrj** [comment]
check this

https://mmdetection.readthedocs.io/en/latest/tutorials/data_pipeline.html

**Comment by alaa-shubbak** [comment]
Hello , I try to resize my images , but it dose not working. 

![resize the images](https://user-images.githubusercontent.com/10245810/129780787-6672551f-bc63-48f2-bb80-d53b5c7f9fc4.JPG)

I am little bit confused with the resize function in mmdetection pipeline ,img_scale is it the new size of the image or the ratio that i multiply with the real image size? and what is the keep ratio function does ? what happens when it is True and what about if it is false?

**Comment by alaa-shubbak** [comment]
in the document of mmdetection , they mention that if there is aproblem of cuda out of memory , it can be solved using the mixed precision training. 
so I try to use this idea by adding the following lines in my config file of  CentriapetalNet 

```
# fp16 settings
fp16 = dict(loss_scale=512.)
```

unfortunately , it dose not working and i got such error massage: 
![error massage in centrailnet pf16](https://user-images.githubusercontent.com/10245810/130240881-0c94726c-418b-4eb8-8bab-2dd0af6b4ada.JPG)

I did not understand the error massage as well as being unable to deal with it .

any one has any idea to help? shall I change the scale of input images again , as I changed it before to so small size 200*200  

please help

**Comment by ZwwWayne** [comment]
with_cp=True should be used in the backbone. gpu_assign_thr should be used in the `MaxIoUAssigner`.

**Comment by alaa-shubbak** [comment]
> with_cp=True should be used in the backbone. gpu_assign_thr should be used in the `MaxIoUAssigner`.

Thank you so much for replaying .. after reading on config file of CentriapetalNet,  i don't think that gpu_assign is possible with  keypoint estimator models such as this Centriapetal , cornerNet and cenetrNet , as all those models do not depend on IOU and anchor boxes .. the basic config of training part (train_cfg=None,) there did have any thing ,as seen in this picture. 

![centrailpetal train config](https://user-images.githubusercontent.com/10245810/131400499-ca4a65a8-e739-4d90-b7f3-6fa0490cfc9e.JPG)

which put me again in the same circle of not knowing how to pre-train such model using my own dataset. 
moreover , i try to use the idea of using `with_cp=True` , i put it in the backbone as bellow: 


![train the centrialpetal](https://user-images.githubusercontent.com/10245810/131401169-ae0a1583-db33-4384-bb85-44c4bc1ab5fd.JPG)

shall i update this part of with_cp and another thing together? 
but it did not work. i am really confused , how can i train such model on my new dataset ? even if there any other repository have a code of centriapetal model , i am interested to give it a try.

**Comment by alaa-shubbak** [comment]
any help please !!!

**Comment by alaa-shubbak** [comment]
hello , i put the line `with_cp=True` in different places in the backbone , as following: 
![centrialpetal error](https://user-images.githubusercontent.com/10245810/131884401-ee8a9ca0-93cb-4055-b7e3-2c7f1a641f91.JPG)

![centrialpetal error2](https://user-images.githubusercontent.com/10245810/131884778-0259340f-37c9-4459-83c9-f72604c39d8e.JPG)

and in the both cases i gor this error message: 
![centripetal error](https://user-images.githubusercontent.com/10245810/131884561-9244c8e7-6ef7-45f3-aaa8-497f6bf5636a.JPG)

could you please let me know exactly on which line shall i put this code on the backbone part?

**Comment by BIGWangYuDong** [comment]
Sorry, I have check the code, and `HourglassNet` did not support with_cp...

**Comment by alaa-shubbak** [comment]
> Sorry, I have check the code, and `HourglassNet` did not support with_cp...

Thank you ..
Then how can I run CentripetalNet on my system. I am working on a machine with 2GPU only .

**Comment by ZwwWayne** [comment]
You can try to use the GPU0 for inference. We may support with_cp in the future.

**Comment by BIGWangYuDong** [comment]
You can try to use AvoidOOM to avoid CUDA out of memory

**Comment by wangliangwu** [comment]
in ${MMDETECTION_HOME}/config/__base__/model/xxx.py
add
with_cp=True,
then the slove maybe solved,I try and I solved my problem

**Comment by wangliangwu** [comment]
like this
model = dict(
    type='RetinaNet',
    pretrained='torchvision://resnet50',
    backbone=dict(
        **with_cp=True,**
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
