### ISSUE TITLE
Strange OOM error

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [open-mmlab/mmdetection#6009]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
3. The bug has not been fixed in the latest version.

**Describe the bug**
During training coco format custom dataset, got OOM error after first time evaluating:

RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 11.17 GiB total capacity; 10.49 GiB already allocated; 12.75 MiB free; 10.83 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', './tools/train.py', '--local_rank=1', '/home/data/yolox_nano_2x48_fuse0828_0901.py', '--launcher', 'pytorch']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************

Actually, about 8G memory used on each gpu. totally 2 GPU.

Model config  basicly is yolox-s one, with modifying lr part and optimizer part.

**Reproduction**

CUDA_VISIBLE_DEVICES=0,1 PORT=29500 ./tools/dist_train/py xxx/_config.py 2

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No  modifications
3. What dataset did you use?

**Environment**

docker environment, version 2.15.1

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RangiLyu** [comment]
Maybe because the number of objects in your custom dataset is larger than coco and this will cost more memory.

**Comment by MoonBunnyZZZ** [comment]
> Maybe because the number of objects in your custom dataset is larger than coco and this will cost more memory.

only one class object and less than 3 gt target per imgae

**Comment by RangiLyu** [comment]
It's weird. Are there any background processes that may take up GPU memory?

**Comment by MoonBunnyZZZ** [comment]
@RangiLyu 
Last night I did the training again and found that during training gpu memory usage was increasing.

log below:
2021-09-02 06:24:56,995 - mmdet - INFO - Epoch [1][123/635]     lr: 5.003e-04,memory: 4411
2021-09-02 06:25:10,046 - mmdet - INFO - Epoch [1][124/635]     lr: 5.084e-04,memory: 4411

2021-09-02 06:52:17,390 - mmdet - INFO - Epoch [2][194/635]     lr: 2.272e-02,memory: 8326
2021-09-02 06:52:20,745 - mmdet - INFO - Epoch [2][195/635]     lr: 2.278e-02,memory: 8326

2021-09-02 07:18:20,690 - mmdet - INFO - Epoch [3][215/635]     lr: 7.292e-02, memory: 9394
2021-09-02 07:18:22,235 - mmdet - INFO - Epoch [3][216/635]     lr: 7.302e-02, memory: 9394

2021-09-02 10:33:34,899 - mmdet - INFO - Epoch [10][469/635]    lr: 1.118e-01, memory: 10335
2021-09-02 10:33:36,398 - mmdet - INFO - Epoch [10][470/635]    lr: 1.118e-01, memory: 10335
I just copy part of log line for show


Once I was afraid of OOM error because the 'memory' number was increasing.But now it settle in 10335.
nvidia-smi settle in 11265MiB / 11439MiB

So why memory usage was increasing?

**Comment by HengYuD** [comment]
I meet similar during my training:

the net config used yolox_x and 3090 with 24G memery
my dataset have about 4000 pictures with size of 600x600

first batchsize=16 and workers =4, it first used about 21G and OOM at epoch2

so I set batchsize=12 , it used on 16G first and OOM at epoch50

now I set batchsize=8 just like the default
 at the beginning it used 11G, now it used about 20G after 20 epochs(now epoch70 )

**Comment by HengYuD** [comment]
> @RangiLyu
> Last night I did the training again and found that during training gpu memory usage was increasing.
> 
> log below:
> 2021-09-02 06:24:56,995 - mmdet - INFO - Epoch [1][123/635] lr: 5.003e-04,memory: 4411
> 2021-09-02 06:25:10,046 - mmdet - INFO - Epoch [1][124/635] lr: 5.084e-04,memory: 4411
> 
> 2021-09-02 06:52:17,390 - mmdet - INFO - Epoch [2][194/635] lr: 2.272e-02,memory: 8326
> 2021-09-02 06:52:20,745 - mmdet - INFO - Epoch [2][195/635] lr: 2.278e-02,memory: 8326
> 
> 2021-09-02 07:18:20,690 - mmdet - INFO - Epoch [3][215/635] lr: 7.292e-02, memory: 9394
> 2021-09-02 07:18:22,235 - mmdet - INFO - Epoch [3][216/635] lr: 7.302e-02, memory: 9394
> 
> 2021-09-02 10:33:34,899 - mmdet - INFO - Epoch [10][469/635] lr: 1.118e-01, memory: 10335
> 2021-09-02 10:33:36,398 - mmdet - INFO - Epoch [10][470/635] lr: 1.118e-01, memory: 10335
> I just copy part of log line for show
> 
> Once I was afraid of OOM error because the 'memory' number was increasing.But now it settle in 10335.
> nvidia-smi settle in 11265MiB / 11439MiB
> 
> So why memory usage was increasing?

maybe the cutmix and mosaic process take expected GPU memery

**Comment by RangiLyu** [comment]
Seems that there is a potential memory leak? @hhaAndroid did you meet a similar problem during training?

**Comment by hhaAndroid** [comment]
@MoonBunnyZZZ You can temporarily turn off multi-scale training to test whether there is a memory leak.

**Comment by igo312** [comment]
@hhaAndroid Does  multi-scale training will occur memory leak?  I using `memory_prifiler` to record the memory usage. It seems pipeline will occur memory leak. Here's my log, after a iter the increment memory seems not be free.
```
| 153 4223.5156 MiB   0.00000 MiB         1           ...
│156 4272.0000 MiB  48.4844 MiB           1           return self.pipeline(data)  
││                                                                                                                        │
Filename: /data/code/research/mmdet/datasets/mycls.py                                 │                                                                                                            │Line #    Mem usage    Increment  Occurrences   Line Contents                                               │=============================================================                                              
│130 4272.2070 MiB 4272.2070 MiB           1       @profile(precision=4, stream=open('./memory_profiler_my│cls.log','w+'))                                                                                             │
```
Here's my memory record plot 
![image](https://user-images.githubusercontent.com/28484395/147473080-52f3b777-1109-4ac2-a4b2-7733b4bb2b43.png)

**Comment by igo312** [comment]
Finally I found the problem. In my own dataset class, I save my img(a `numpy.array`) as element of `dicts`. In somehow, it will cause memory leak, and the problem is gone after I return the `img` directly.
```
# before
      for i, info in enumerate(img_info):
          img = self._load_img(info['id'])
          img_info[i]['img'] = img
      return img_info
# after 
      imgs = [] 
      for i, info in enumerate(img_info):
         img = self._load_img(info['id'])
          imgs.append(img)
      return img_info, imgs
```
