### ISSUE TITLE
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory   

### ISSUE THREAD

**Issue by mathshangw** [open-mmlab/mmdetection#6229]
I got this error 

 

        from mmdet.apis import multi_gpu_test, single_gpu_test
      File "/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
        from .inference import (async_inference_detector, inference_detector,
      File "/mmdetection/mmdet/apis/inference.py", line 6, in <module>
        from mmcv.ops import RoIPool
      File "/home/.local/lib/python3.6/site-packages/mmcv/ops/__init__.py", line 1, in <module>
        from .bbox import bbox_overlaps
      File "/home/.local/lib/python3.6/site-packages/mmcv/ops/bbox.py", line 3, in <module>
        ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
      File "/home/user/.local/lib/python3.6/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
        ext = importlib.import_module('mmcv.' + name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory   
     

and my Cuda is 

    NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0

i need to use Cuda 11.0 instead of 10.2 but don't know why it is read the old version of Cuda

**Comment by zhouzaida** [comment]
please check whether the CUDA/GCC runtimes are the same as those used for compiling mmcv.

**Comment by mathshangw** [comment]
Excuse me how can I check it ?

**Comment by zhouzaida** [comment]
Print the cuda runtime version by `nvcc --version`. And what command did you use to install mmcv-full?

**Comment by zhouzaida** [comment]
Maybe you installed mmcv for cuda11 but your runtime cuda is 10.2, so it won't find

**Comment by mathshangw** [comment]
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

i installed `pip3 install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html`
so i need to install mmcv-full with cuda 10.2 ? but where version 10.2 come from and nvcc is 9 and i have cuda 11 ?

Thanks for help

**Comment by zhouzaida** [comment]
Could you provide the following environments?

```bash
echo $PATH
echo $LD_LIBRARY_PATH
```

**Comment by mathshangw** [comment]
thanks i solved it by re-install mmcv-full for cuda 10.2

**Comment by mathshangw** [comment]
i re-installed mmcv-full and torch for cuda 11.0 and worked finally
