### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by youyousky** [open-mmlab/mmdetection#719]
Hello, when I train the model by the coco2017 dataset, it always gives me this error.  I use only one GPU to train the model. The dataset is not changed and no matter what model I train, it always get the error following: 
(open-mmlab) pg@pg:~/mmdetection$  python3.7 tools/train.py configs/htc/htc_r50_fpn_1x.py
2019-05-26 17:47:28,568 - INFO - Distributed training: False
2019-05-26 17:47:29,018 - INFO - load model from: modelzoo://resnet50
2019-05-26 17:47:29,134 - WARNING - unexpected key in source state_dict: fc.weight, fc.bias

missing keys in source state_dict: layer2.0.bn1.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer3.4.bn1.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer2.3.bn1.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, bn1.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer3.0.bn2.num_batches_tracked

loading annotations into memory...
Done (t=7.13s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 95, in <module>
    main()
  File "tools/train.py", line 91, in main
    logger=logger)
  File "/home/pg/mmdetection/mmdet/apis/train.py", line 61, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/pg/mmdetection/mmdet/apis/train.py", line 185, in _non_dist_train
    model = MMDataParallel(model, device_ids=range(cfg.gpus)).cuda()
  File "/home/pg/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 136, in __init__
    self.module.cuda(device_ids[0])
  File "/home/pg/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/pg/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/pg/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/home/pg/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 199, in _apply
    param.data = fn(param.data)
  File "/home/pg/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 265, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: unknown error

**Comment by zhang1992wen1023** [comment]
same errors

**Comment by youyousky** [comment]
It may be a problem with the configuration of the computer itself. I changed another computer and the problem was gone.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yaoglish"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午2:54
收件人: "open-mmlab/mmdetection"<mmdetection@noreply.github.com&gt;; 
抄送: "雄鹰"<254968083@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [open-mmlab/mmdetection] RuntimeError: CUDA error: unknown error (#719)




same errors
